import{a as y,S as f,i}from"./assets/vendor-40038228.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&e(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const n={form:document.querySelector("#search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),input:document.querySelector("input"),loadMoreBtn:document.querySelector(".load-more-btn"),endOfCollection:document.querySelector(".end-of-collection")};async function d(s,r){const a=new URLSearchParams({key:"41611765-95d63315582311c92a96eb89d",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}),{data:e}=await y.get(`https://pixabay.com/api/?${a}`);return e}function p(s){const r=s.reduce((a,e)=>(a+=`<li class="gallery-item">
    <a href=${e.largeImageURL}> 
      <img class="gallery-img" src =${e.webformatURL} alt=${e.tags}/>
    </a>
    <div class="gallery-text-box">
      <p>likes: <span class="text-value">${e.likes}</span></p>
      <p>views: <span class="text-value">${e.views}</span></p>
      <p>comments: <span class="text-value">${e.comments}</span></p>
      <p>downloads: <span class="text-value">${e.downloads}</span></p>
    </div>
    </li>`,a),"");n.gallery.insertAdjacentHTML("beforeend",r)}function m(){n.gallery.innerHTML=""}const u=new f(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});u.refresh();function g(){window.scroll({top:0,left:0,behavior:"smooth"})}let l=1,h;n.loadMoreBtn.style.display="none";n.form.addEventListener("submit",async s=>{s.preventDefault(),n.loadMoreBtn.style.display="none",m(),l=1;let r=n.input.value.trim();if(!r){i.error({position:"topRight",message:"Input empty! Try again."});return}try{const{hits:a,totalHits:e}=await d(r,l);if(e===0){i.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."});return}p(a),n.loadMoreBtn.style.display="block",u.refresh(),l===Math.ceil(e/40)&&(i.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.loadMoreBtn.style.display="none")}catch(a){i.error({position:"topRight",message:"Please try again."}),console.log(a)}});n.loadMoreBtn.addEventListener("click",async()=>{l++;try{const{hits:s,totalHits:r}=await d(h,l);p(s),u.refresh(),g(),l===Math.ceil(r/40)&&(i.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.loadMoreBtn.style.display="none")}catch(s){console.log(s)}});
//# sourceMappingURL=commonHelpers.js.map
