import{a as f,S as m,i as u}from"./assets/vendor-40038228.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const s={form:document.querySelector("#search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),input:document.querySelector("input"),loadMoreBtn:document.querySelector(".load-more-btn"),endOfCollection:document.querySelector(".end-of-collection")};async function p(a,t){const n=new URLSearchParams({key:"41611765-95d63315582311c92a96eb89d",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t}),{data:r}=await f.get(`https://pixabay.com/api/?${n}`);return r}function y(a){const t=a.reduce((n,r)=>(n+=`<li class="gallery-item">
    <a href=${r.largeImageURL}> 
      <img class="gallery-img" src =${r.webformatURL} alt=${r.tags}/>
    </a>
    <div class="gallery-text-box">
      <p>likes: <span class="text-value">${r.likes}</span></p>
      <p>views: <span class="text-value">${r.views}</span></p>
      <p>comments: <span class="text-value">${r.comments}</span></p>
      <p>downloads: <span class="text-value">${r.downloads}</span></p>
    </div>
    </li>`,n),"");s.gallery.insertAdjacentHTML("beforeend",t)}function g(){s.gallery.innerHTML=""}const d=new m(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});d.refresh();let l=1,i;s.loadMoreBtn.style.display="none";s.form.addEventListener("submit",async a=>{if(a.preventDefault(),s.loadMoreBtn.style.display="none",g(),l=1,i=s.input.value.trim(),!i){u.error({position:"topRight",message:"Input empty! Try again."});return}try{const{hits:t,totalHits:n}=await p(i,l);if(t.length===0){u.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."});return}y(t),s.loadMoreBtn.style.display="block",d.refresh()}catch(t){console.log(t)}});s.loadMoreBtn.addEventListener("click",async()=>{l++;try{const{hits:a,totalHits:t}=await p(i,l);y(a),d.refresh(),l>Math.ceil(t/perPage)&&(u.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),s.loadMoreBtn.style.display="none")}catch(a){console.log(a)}});
//# sourceMappingURL=commonHelpers.js.map
