import{a as f,S as g,i as h}from"./assets/vendor-bad0427b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const u=document.getElementById("search-form"),n=document.getElementById("gallery"),y=document.querySelector(".loader"),m=document.querySelector("input"),d=document.querySelector(".load-more-btn"),b=document.querySelector(".end-of-collection");let r=1,l={key:"41611765-95d63315582311c92a96eb89d",q:"cat",image_type:"photo",orientation:"horizontal",safesearch:!0};d.style.display="none";u.addEventListener("click",async a=>{if(a.preventDefault(),a.target.type==="submit"){l.q=m.value,r=1;const o=new URLSearchParams({...l,page:r});await p(o)}u.reset()});d.addEventListener("click",async()=>{r++;const a=new URLSearchParams({...l,page:r});await p(a)});u.addEventListener("submit",async a=>{a.preventDefault(),l.q=m.value,r=1;const o=new URLSearchParams({...l,page:r});await p(o),n.children.length>0?d.style.display="block":d.style.display="none"});async function p(a){y.style.display="block",n.style.display="none";try{const o=await f.get(`https://pixabay.com/api/?${a}`),{hits:c}=o.data;if(c.length>0){const i=c.reduce((t,s)=>(t+=`<li class="gallery-item">
          <a href=${s.largeImageURL}> 
            <img class="gallery-img" src =${s.webformatURL} alt=${s.tags}/>
          </a>
          <div class="gallery-text-box">
            <p>likes: <span class="text-value">${s.likes}</span></p>
            <p>views: <span class="text-value">${s.views}</span></p>
            <p>comments: <span class="text-value">${s.comments}</span></p>
            <p>downloads: <span class="text-value">${s.downloads}</span></p>
        </div>
        </li>`,t),"");n.innerHTML=i,new g(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0}).refresh(),v()}else n.style.display="none",b.style.display="block",h.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(o){console.error(o)}finally{y.style.display="none",n.style.display="flex"}}function v(){window.scroll({top:0,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
